workspace(name = "main")

local_repository(
    name = "sample_java_rules",
    path = "../sample_java_rules",
)

local_repository(
    name = "sample_java_config",
    path = "../sample_java_config",
)

load("@sample_java_config//:autoconfigure.bzl", "autoconfigure")

# Could be in WORKSPACE suffix via Bazel automatically loading it.
autoconfigure(
    name = "local_sample_java",
    found = True,
)

# No further configuration.
