workspace(name = "main")

local_repository(
    name = "sample_java_rules",
    path = "../sample_java_rules",
)

local_repository(
    name = "sample_java_config",
    path = "../sample_java_config",
)

load("@sample_java_config//:local.bzl", "local")

# Added as project-specific configuration: assumes all machines are set up the same.
local(
    name = "local_sample_java",
    path = "/usr/bin/foo",
)

# Even with this in the WORKSPACE suffix, the previously-configured toolchain would be used.
load("@sample_java_config//:autoconfigure.bzl", "autoconfigure")

autoconfigure(
    name = "local_sample_java",
    found = True,
)
