workspace(name = "main")

local_repository(
    name = "sample_java_rules",
    path = "../sample_java_rules",
)

local_repository(
    name = "local",
    path = "../local",
)

load("@local//:autoconfigure.bzl", "autoconfigure")

autoconfigure(name = "local_sample_java")

# No further configuration.
